// Auto-generated by `supabase gen types typescript`
// Run `pnpm db:generate-types` from the monorepo root to regenerate.
//
// Placeholder until Supabase project is connected and migrations applied.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Database = {
  public: {
    Tables: {
      agences: {
        Row: {
          id: string;
          nom: string;
          ville: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          nom?: string;
          ville?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          nom?: string;
          ville?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          id: string;
          role: "client" | "operateur" | "proprietaire" | "livreur" | "agent_immobilier";
          nom: string;
          telephone: string;
          email: string | null;
          agence_id: string | null;
          statut_verification: "non_verifie" | "documents_soumis" | "verifie" | "rejete";
          piece_identite_url: string | null;
          permis_conduire_url: string | null;
          date_naissance: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          role: "client" | "operateur" | "proprietaire" | "livreur" | "agent_immobilier";
          nom: string;
          telephone: string;
          email?: string | null;
          agence_id?: string | null;
          statut_verification?: "non_verifie" | "documents_soumis" | "verifie" | "rejete";
          piece_identite_url?: string | null;
          permis_conduire_url?: string | null;
          date_naissance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: "client" | "operateur" | "proprietaire" | "livreur" | "agent_immobilier";
          nom?: string;
          telephone?: string;
          email?: string | null;
          agence_id?: string | null;
          statut_verification?: "non_verifie" | "documents_soumis" | "verifie" | "rejete";
          piece_identite_url?: string | null;
          permis_conduire_url?: string | null;
          date_naissance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chauffeurs: {
        Row: {
          id: string;
          nom: string;
          telephone: string;
          permis_professionnel_url: string | null;
          agence_id: string | null;
          actif: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          nom: string;
          telephone: string;
          permis_professionnel_url?: string | null;
          agence_id?: string | null;
          actif?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          nom?: string;
          telephone?: string;
          permis_professionnel_url?: string | null;
          agence_id?: string | null;
          actif?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      vehicules: {
        Row: {
          id: string;
          agence_id: string | null;
          categorie: "leger" | "car" | "minibus";
          marque: string;
          modele: string;
          annee: number | null;
          nb_places: number | null;
          climatisation: boolean;
          boite: "automatique" | "manuelle" | null;
          carburant: string | null;
          kilometrage: number | null;
          localisation: string | null;
          latitude: number | null;
          longitude: number | null;
          prix_journalier: number | null;
          prix_mensuel: number | null;
          prix_vente: number | null;
          chauffeur_disponible: boolean;
          description: string | null;
          carte_grise_url: string | null;
          certificat_non_gage_url: string | null;
          statut: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agence_id?: string | null;
          categorie: "leger" | "car" | "minibus";
          marque: string;
          modele: string;
          annee?: number | null;
          nb_places?: number | null;
          climatisation?: boolean;
          boite?: "automatique" | "manuelle" | null;
          carburant?: string | null;
          kilometrage?: number | null;
          localisation?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          prix_journalier?: number | null;
          prix_mensuel?: number | null;
          prix_vente?: number | null;
          chauffeur_disponible?: boolean;
          description?: string | null;
          carte_grise_url?: string | null;
          certificat_non_gage_url?: string | null;
          statut?: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agence_id?: string | null;
          categorie?: "leger" | "car" | "minibus";
          marque?: string;
          modele?: string;
          annee?: number | null;
          nb_places?: number | null;
          climatisation?: boolean;
          boite?: "automatique" | "manuelle" | null;
          carburant?: string | null;
          kilometrage?: number | null;
          localisation?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          prix_journalier?: number | null;
          prix_mensuel?: number | null;
          prix_vente?: number | null;
          chauffeur_disponible?: boolean;
          description?: string | null;
          carte_grise_url?: string | null;
          certificat_non_gage_url?: string | null;
          statut?: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vehicule_photos: {
        Row: {
          id: string;
          vehicule_id: string;
          url: string;
          ordre: number;
        };
        Insert: {
          id?: string;
          vehicule_id: string;
          url: string;
          ordre?: number;
        };
        Update: {
          id?: string;
          vehicule_id?: string;
          url?: string;
          ordre?: number;
        };
        Relationships: [];
      };
      disponibilites_vehicule: {
        Row: {
          id: string;
          vehicule_id: string;
          periode: string;
          type: "reservation" | "maintenance" | "bloque";
        };
        Insert: {
          id?: string;
          vehicule_id: string;
          periode: string;
          type?: "reservation" | "maintenance" | "bloque";
        };
        Update: {
          id?: string;
          vehicule_id?: string;
          periode?: string;
          type?: "reservation" | "maintenance" | "bloque";
        };
        Relationships: [];
      };
      disponibilites_chauffeur: {
        Row: {
          id: string;
          chauffeur_id: string;
          periode: string;
        };
        Insert: {
          id?: string;
          chauffeur_id: string;
          periode: string;
        };
        Update: {
          id?: string;
          chauffeur_id?: string;
          periode?: string;
        };
        Relationships: [];
      };
      demandes_transport: {
        Row: {
          id: string;
          client_id: string;
          vehicule_id: string | null;
          type: "reservation_directe" | "devis";
          categorie: "classique" | "evenementiel" | "scolaire" | "personnel";
          periode: string | null;
          ville_depart: string | null;
          destination: string | null;
          avec_chauffeur: boolean;
          chauffeur_id: string | null;
          montant: number | null;
          caution: number | null;
          methode_paiement: "cinetpay" | "stripe" | "agence" | null;
          statut: "en_attente_paiement" | "en_attente_validation" | "acceptee" | "refusee" | "annulee" | "terminee";
          devis_expire_at: string | null;
          etat_lieux_depart_photos: string[] | null;
          etat_lieux_retour_photos: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          vehicule_id?: string | null;
          type: "reservation_directe" | "devis";
          categorie: "classique" | "evenementiel" | "scolaire" | "personnel";
          periode?: string | null;
          ville_depart?: string | null;
          destination?: string | null;
          avec_chauffeur?: boolean;
          chauffeur_id?: string | null;
          montant?: number | null;
          caution?: number | null;
          methode_paiement?: "cinetpay" | "stripe" | "agence" | null;
          statut?: "en_attente_paiement" | "en_attente_validation" | "acceptee" | "refusee" | "annulee" | "terminee";
          devis_expire_at?: string | null;
          etat_lieux_depart_photos?: string[] | null;
          etat_lieux_retour_photos?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          vehicule_id?: string | null;
          type?: "reservation_directe" | "devis";
          categorie?: "classique" | "evenementiel" | "scolaire" | "personnel";
          periode?: string | null;
          ville_depart?: string | null;
          destination?: string | null;
          avec_chauffeur?: boolean;
          chauffeur_id?: string | null;
          montant?: number | null;
          caution?: number | null;
          methode_paiement?: "cinetpay" | "stripe" | "agence" | null;
          statut?: "en_attente_paiement" | "en_attente_validation" | "acceptee" | "refusee" | "annulee" | "terminee";
          devis_expire_at?: string | null;
          etat_lieux_depart_photos?: string[] | null;
          etat_lieux_retour_photos?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      conducteurs_secondaires: {
        Row: {
          id: string;
          demande_transport_id: string;
          nom: string;
          permis_conduire_url: string;
          statut_verification: "documents_soumis" | "verifie" | "rejete";
          created_at: string;
        };
        Insert: {
          id?: string;
          demande_transport_id: string;
          nom: string;
          permis_conduire_url: string;
          statut_verification?: "documents_soumis" | "verifie" | "rejete";
          created_at?: string;
        };
        Update: {
          id?: string;
          demande_transport_id?: string;
          nom?: string;
          permis_conduire_url?: string;
          statut_verification?: "documents_soumis" | "verifie" | "rejete";
          created_at?: string;
        };
        Relationships: [];
      };
      contrats_recurrents: {
        Row: {
          id: string;
          client_id: string;
          categorie: "scolaire" | "personnel";
          vehicule_id: string | null;
          date_debut: string;
          date_fin: string | null;
          frequence_facturation: "mensuelle" | "trimestrielle" | "annuelle" | null;
          montant_periodique: number | null;
          statut: "actif" | "suspendu" | "resilie";
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          categorie: "scolaire" | "personnel";
          vehicule_id?: string | null;
          date_debut: string;
          date_fin?: string | null;
          frequence_facturation?: "mensuelle" | "trimestrielle" | "annuelle" | null;
          montant_periodique?: number | null;
          statut?: "actif" | "suspendu" | "resilie";
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          categorie?: "scolaire" | "personnel";
          vehicule_id?: string | null;
          date_debut?: string;
          date_fin?: string | null;
          frequence_facturation?: "mensuelle" | "trimestrielle" | "annuelle" | null;
          montant_periodique?: number | null;
          statut?: "actif" | "suspendu" | "resilie";
          created_at?: string;
        };
        Relationships: [];
      };
      avis_transport: {
        Row: {
          id: string;
          demande_id: string;
          note: number;
          commentaire: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          demande_id: string;
          note: number;
          commentaire?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          demande_id?: string;
          note?: number;
          commentaire?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      livreurs: {
        Row: {
          id: string;
          user_id: string;
          zone_couverture: string | null;
          capacite_max_par_jour: number;
          actif: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          zone_couverture?: string | null;
          capacite_max_par_jour?: number;
          actif?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          zone_couverture?: string | null;
          capacite_max_par_jour?: number;
          actif?: boolean;
        };
        Relationships: [];
      };
      expeditions: {
        Row: {
          id: string;
          client_id: string;
          numero_suivi: string;
          expediteur_nom: string;
          expediteur_contact: string;
          destinataire_nom: string;
          destinataire_contact: string;
          adresse_collecte: string;
          adresse_livraison: string;
          poids_kg: number | null;
          dimensions: string | null;
          nature_colis: string | null;
          valeur_declaree: number | null;
          mode: "standard" | "express" | "meme_jour" | "programmee";
          zone: "intracommunale" | "intercommunale" | "nationale";
          prix: number | null;
          livreur_id: string | null;
          statut: "creee" | "prise_en_charge" | "en_transit" | "livree" | "echec_livraison";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          numero_suivi: string;
          expediteur_nom: string;
          expediteur_contact: string;
          destinataire_nom: string;
          destinataire_contact: string;
          adresse_collecte: string;
          adresse_livraison: string;
          poids_kg?: number | null;
          dimensions?: string | null;
          nature_colis?: string | null;
          valeur_declaree?: number | null;
          mode: "standard" | "express" | "meme_jour" | "programmee";
          zone: "intracommunale" | "intercommunale" | "nationale";
          prix?: number | null;
          livreur_id?: string | null;
          statut?: "creee" | "prise_en_charge" | "en_transit" | "livree" | "echec_livraison";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          numero_suivi?: string;
          expediteur_nom?: string;
          expediteur_contact?: string;
          destinataire_nom?: string;
          destinataire_contact?: string;
          adresse_collecte?: string;
          adresse_livraison?: string;
          poids_kg?: number | null;
          dimensions?: string | null;
          nature_colis?: string | null;
          valeur_declaree?: number | null;
          mode?: "standard" | "express" | "meme_jour" | "programmee";
          zone?: "intracommunale" | "intercommunale" | "nationale";
          prix?: number | null;
          livreur_id?: string | null;
          statut?: "creee" | "prise_en_charge" | "en_transit" | "livree" | "echec_livraison";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expedition_statut_historique: {
        Row: {
          id: string;
          expedition_id: string;
          statut: string;
          horodatage: string;
        };
        Insert: {
          id?: string;
          expedition_id: string;
          statut: string;
          horodatage?: string;
        };
        Update: {
          id?: string;
          expedition_id?: string;
          statut?: string;
          horodatage?: string;
        };
        Relationships: [];
      };
      agents_immobiliers: {
        Row: {
          id: string;
          user_id: string;
          zone_couverture: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          zone_couverture?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          zone_couverture?: string | null;
        };
        Relationships: [];
      };
      biens: {
        Row: {
          id: string;
          type: "terrain" | "maison" | "appartement" | "bureau";
          transaction: "vente" | "location";
          prix: number;
          nb_chambres: number | null;
          surface_m2: number | null;
          localisation: string;
          latitude: number | null;
          longitude: number | null;
          description: string | null;
          agent_id: string | null;
          statut: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: "terrain" | "maison" | "appartement" | "bureau";
          transaction: "vente" | "location";
          prix: number;
          nb_chambres?: number | null;
          surface_m2?: number | null;
          localisation: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          agent_id?: string | null;
          statut?: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: "terrain" | "maison" | "appartement" | "bureau";
          transaction?: "vente" | "location";
          prix?: number;
          nb_chambres?: number | null;
          surface_m2?: number | null;
          localisation?: string;
          latitude?: number | null;
          longitude?: number | null;
          description?: string | null;
          agent_id?: string | null;
          statut?: "disponible" | "reserve" | "loue" | "vendu" | "indisponible";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bien_medias: {
        Row: {
          id: string;
          bien_id: string;
          type: "photo" | "video";
          url: string;
          ordre: number;
        };
        Insert: {
          id?: string;
          bien_id: string;
          type: "photo" | "video";
          url: string;
          ordre?: number;
        };
        Update: {
          id?: string;
          bien_id?: string;
          type?: "photo" | "video";
          url?: string;
          ordre?: number;
        };
        Relationships: [];
      };
      visites: {
        Row: {
          id: string;
          bien_id: string;
          client_id: string;
          agent_id: string;
          creneau: string;
          statut: "proposee" | "confirmee" | "realisee" | "annulee";
          created_at: string;
        };
        Insert: {
          id?: string;
          bien_id: string;
          client_id: string;
          agent_id: string;
          creneau: string;
          statut?: "proposee" | "confirmee" | "realisee" | "annulee";
          created_at?: string;
        };
        Update: {
          id?: string;
          bien_id?: string;
          client_id?: string;
          agent_id?: string;
          creneau?: string;
          statut?: "proposee" | "confirmee" | "realisee" | "annulee";
          created_at?: string;
        };
        Relationships: [];
      };
      demandes_immobilier: {
        Row: {
          id: string;
          bien_id: string;
          client_id: string;
          agent_id: string | null;
          type: "information" | "visite" | "offre";
          montant_offre: number | null;
          statut: "en_attente" | "en_cours_traitement" | "visite_programmee" | "offre_soumise" | "acceptee" | "refusee" | "annulee" | "finalisee";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bien_id: string;
          client_id: string;
          agent_id?: string | null;
          type: "information" | "visite" | "offre";
          montant_offre?: number | null;
          statut?: "en_attente" | "en_cours_traitement" | "visite_programmee" | "offre_soumise" | "acceptee" | "refusee" | "annulee" | "finalisee";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bien_id?: string;
          client_id?: string;
          agent_id?: string | null;
          type?: "information" | "visite" | "offre";
          montant_offre?: number | null;
          statut?: "en_attente" | "en_cours_traitement" | "visite_programmee" | "offre_soumise" | "acceptee" | "refusee" | "annulee" | "finalisee";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      dossiers_voyage: {
        Row: {
          id: string;
          client_id: string;
          type: "etudes" | "tourisme_visa";
          pays_cible: string;
          conseiller_id: string | null;
          statut: "soumis" | "en_cours_traitement" | "pieces_complementaires_requises" | "finalise";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          type: "etudes" | "tourisme_visa";
          pays_cible: string;
          conseiller_id?: string | null;
          statut?: "soumis" | "en_cours_traitement" | "pieces_complementaires_requises" | "finalise";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          type?: "etudes" | "tourisme_visa";
          pays_cible?: string;
          conseiller_id?: string | null;
          statut?: "soumis" | "en_cours_traitement" | "pieces_complementaires_requises" | "finalise";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      documents_dossier_voyage: {
        Row: {
          id: string;
          dossier_id: string;
          type_document: string;
          url: string;
          statut: "soumis" | "valide" | "rejete";
          created_at: string;
        };
        Insert: {
          id?: string;
          dossier_id: string;
          type_document: string;
          url: string;
          statut?: "soumis" | "valide" | "rejete";
          created_at?: string;
        };
        Update: {
          id?: string;
          dossier_id?: string;
          type_document?: string;
          url?: string;
          statut?: "soumis" | "valide" | "rejete";
          created_at?: string;
        };
        Relationships: [];
      };
      paiements: {
        Row: {
          id: string;
          module: "transport" | "livraison" | "immobilier" | "voyage";
          reference_table: string;
          reference_id: string;
          type: "montant" | "caution" | "acompte" | "commission";
          montant: number;
          methode: "cinetpay" | "stripe" | "agence" | "virement";
          statut: "en_attente" | "capture" | "echoue" | "rembourse";
          webhook_reference: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          module: "transport" | "livraison" | "immobilier" | "voyage";
          reference_table: string;
          reference_id: string;
          type: "montant" | "caution" | "acompte" | "commission";
          montant: number;
          methode: "cinetpay" | "stripe" | "agence" | "virement";
          statut?: "en_attente" | "capture" | "echoue" | "rembourse";
          webhook_reference?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          module?: "transport" | "livraison" | "immobilier" | "voyage";
          reference_table?: string;
          reference_id?: string;
          type?: "montant" | "caution" | "acompte" | "commission";
          montant?: number;
          methode?: "cinetpay" | "stripe" | "agence" | "virement";
          statut?: "en_attente" | "capture" | "echoue" | "rembourse";
          webhook_reference?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications_log: {
        Row: {
          id: string;
          user_id: string;
          canal: "whatsapp" | "sms" | "push" | "email";
          evenement: string;
          contenu: string | null;
          statut_envoi: "envoye" | "echoue" | "lu";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          canal: "whatsapp" | "sms" | "push" | "email";
          evenement: string;
          contenu?: string | null;
          statut_envoi?: "envoye" | "echoue" | "lu";
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          canal?: "whatsapp" | "sms" | "push" | "email";
          evenement?: string;
          contenu?: string | null;
          statut_envoi?: "envoye" | "echoue" | "lu";
          created_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          cible_table: string | null;
          cible_id: string | null;
          details: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          cible_table?: string | null;
          cible_id?: string | null;
          details?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          cible_table?: string | null;
          cible_id?: string | null;
          details?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
